variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CLIENT_TIMEOUT: 600
  COMPOSE_HTTP_TIMEOUT: 600
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

stages:
  - build
  - test
  - deploy
  - notify

build_job:
   stage: build
   image: docker:20.10.16
   services:
       - docker:20.10.16-dind
   script:
       - docker build -t ex-build-dev:latest .

test_job:
  stage: test
  image: python:3.11
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends gcc python3-dev
    - pip install -r $CI_PROJECT_DIR/requirements.txt pytest pytest-cov
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR/todo_project
    - cd $CI_PROJECT_DIR
    - pytest --cov=./ --cov-report=xml -v $CI_PROJECT_DIR/tests/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage.xml
    expire_in: 1 week

sast_job:
  stage: test
  image: python:3.11
  before_script:
    - pip install bandit
  script:
    - bandit -r $CI_PROJECT_DIR/todo_project
  artifacts:
    paths:
      - $CI_PROJECT_DIR/bandit_output.txt
    expire_in: 1 week

dependency_check_job:
  stage: test
  image: owasp/dependency-check
  script:
    - dependency-check.sh --project "Gestao-Tarefas" --scan $CI_PROJECT_DIR --format "ALL" --out $CI_PROJECT_DIR/dependency-check-report
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dependency-check-report
    expire_in: 1 week

deploy_job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "Remove anterior"
    - PORT_CONTAINERS=$(docker ps --filter "publish=8081" -q)
    - echo $PORT_CONTAINERS
    - if [ -n "$PORT_CONTAINERS" ]; then
        docker stop $PORT_CONTAINERS;
        docker rm $PORT_CONTAINERS;
        sleep 5;
      fi
  script:
    - echo "Deploying the app"
    - docker run -d -p 8081:8080 ex-build-dev:latest

review_job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Creating temporary review environment"
    - docker run -d -p 8082:8080 ex-build-dev:latest

deploy_stage:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Deploying the app to stage"
    - docker run -d -p 8080:8080 ex-build-dev:latest

dast_job:
  stage: test
  image: owasp/zap2docker-stable
  script:
    - zap-baseline.py -t http://localhost:8080 -r zap_report.html
  artifacts:
    paths:
      - zap_report.html
    expire_in: 1 week
  needs:
    - deploy_stage
